### ISSUE TITLE
Problems occurred  when "make runtest"

### ISSUE THREAD

**Issue by liruihao** [TheLegendAli/DeepLab-Context2#4]
Dear Ali,

I tried to compile DeepLab-Context2. When I used "make all -j8", "make test", all test passed. However, when I tried to "make runtest". Problems occurred as displayed blow. Do you know how can I fix it? Should  I use cmake to compile Deeplab-Context2? Thank you very much for your time.

 

[ RUN      ] LayerFactoryTest/0.TestCreateLayer
*** Aborted at 1480007884 (unix time) try "date -d @1480007884" if you are using GNU date ***
PC: @     0x2b438136ad1c (unknown)
*** SIGSEGV (@0x0) received by PID 13173 (TID 0x2b437a3d9640) from PID 0; stack trace: ***
    @     0x2b43810da330 (unknown)
    @     0x2b438136ad1c (unknown)
    @     0x2b43802153a1 deallocate()
    @     0x2b43802d6018 caffe::DenseCRFLayer<>::DeAllocateAllData()
    @     0x2b43802da51c caffe::DenseCRFLayer<>::~DenseCRFLayer()
    @     0x2b43802dab49 caffe::DenseCRFLayer<>::~DenseCRFLayer()
    @           0x60497b caffe::LayerFactoryTest_TestCreateLayer_Test<>::TestBody()
    @           0x8cb0d3 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8c1db7 testing::Test::Run()
    @           0x8c1e5e testing::TestInfo::Run()
    @           0x8c1f65 testing::TestCase::Run()
    @           0x8c52a8 testing::internal::UnitTestImpl::RunAllTests()
    @           0x8c5537 testing::UnitTest::Run()
    @           0x46bbef main
    @     0x2b4381309f45 (unknown)
    @           0x4735d9 (unknown)
make: *** [runtest] Segmentation fault (core dumped)

Best regards,

Ruihao

**Comment by liruihao** [comment]
Besides, I use Cuda7.5.18 and cudnn V4. The GPU I use is GeForce TITAN X.

I find that in /src/caffe/layers, there is only densecrf_layer.cpp and there is no densecrf_layer.cu. Is this why we can not pass "make runtest"?

**Comment by TheLegendAli** [comment]
There is a problem with testrun, we have to update it. But deeplab should work regardless if make all works.

**Comment by liruihao** [comment]
Thank you very much for your time.
